More porting

diff --git a/cctools/configure b/cctools/configure
--- a/cctools/configure
+++ b/cctools/configure
@@ -669,8 +669,8 @@ TAPI_DEF
 TAPI_LIB
 XAR_LIB
 FTS_LIB
-BLOCKS_RUNTIME_LIB
 DISPATCH_LIB
+BLOCKS_RUNTIME_LIB
 LLVM_LIB_DIR
 LLVM_INCLUDE_DIR
 LTO_LIB
@@ -18577,7 +18577,109 @@ printf "%s\n" "$as_me: WARNING: llvm-config not found, disabling LTO support" >&
 
 LDFLAGS="$LDFLAGS $LTO_RPATH"
 
+### Check for Blocks Runtime library ###
+
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for _Block_release in -lBlocksRuntime" >&5
+printf %s "checking for _Block_release in -lBlocksRuntime... " >&6; }
+if test ${ac_cv_lib_BlocksRuntime__Block_release+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lBlocksRuntime  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char _Block_release ();
+int
+main (void)
+{
+return _Block_release ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_lib_BlocksRuntime__Block_release=yes
+else $as_nop
+  ac_cv_lib_BlocksRuntime__Block_release=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_BlocksRuntime__Block_release" >&5
+printf "%s\n" "$ac_cv_lib_BlocksRuntime__Block_release" >&6; }
+if test "x$ac_cv_lib_BlocksRuntime__Block_release" = xyes
+then :
+  BLOCKS_RUNTIME_LIB=-lBlocksRuntime
+else $as_nop
+
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for _Block_release in -lc" >&5
+printf %s "checking for _Block_release in -lc... " >&6; }
+if test ${ac_cv_lib_c__Block_release+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lc  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char _Block_release ();
+int
+main (void)
+{
+return _Block_release ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_lib_c__Block_release=yes
+else $as_nop
+  ac_cv_lib_c__Block_release=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_c__Block_release" >&5
+printf "%s\n" "$ac_cv_lib_c__Block_release" >&6; }
+if test "x$ac_cv_lib_c__Block_release" = xyes
+then :
+  printf "%s\n" "#define HAVE_LIBC 1" >>confdefs.h
+
+  LIBS="-lc $LIBS"
+
+else $as_nop
+
+      echo "Required library liblocksruntime not installed" >&2
+      exit 1
+
+fi
+
+
+
+fi
+
+
+
 ### Check for dispatch library ###
+
+# FreeBSD requires -lBlocksRuntime for -ldispatch
+if test "x$isdarwin" != "xyes"; then
+  ORIGLDFLAGS=$LDFLAGS
+  LDFLAGS="$LDFLAGS -lBlocksRuntime"
+fi
 
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for dispatch_once in -ldispatch" >&5
 printf %s "checking for dispatch_once in -ldispatch... " >&6; }
@@ -18687,102 +18789,9 @@ fi
 
 
 
-### Check for Blocks Runtime library ###
-
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for _Block_release in -lBlocksRuntime" >&5
-printf %s "checking for _Block_release in -lBlocksRuntime... " >&6; }
-if test ${ac_cv_lib_BlocksRuntime__Block_release+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lBlocksRuntime  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char _Block_release ();
-int
-main (void)
-{
-return _Block_release ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_BlocksRuntime__Block_release=yes
-else $as_nop
-  ac_cv_lib_BlocksRuntime__Block_release=no
+if test "x$isdarwin" != "xyes"; then
+  LDFLAGS=$ORIGLDFLAGS
 fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_BlocksRuntime__Block_release" >&5
-printf "%s\n" "$ac_cv_lib_BlocksRuntime__Block_release" >&6; }
-if test "x$ac_cv_lib_BlocksRuntime__Block_release" = xyes
-then :
-  BLOCKS_RUNTIME_LIB=-lBlocksRuntime
-else $as_nop
-
-    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for _Block_release in -lc" >&5
-printf %s "checking for _Block_release in -lc... " >&6; }
-if test ${ac_cv_lib_c__Block_release+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lc  $LIBS"
-cat confdefs.h - <<_ACEOF >conftest.$ac_ext
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-char _Block_release ();
-int
-main (void)
-{
-return _Block_release ();
-  ;
-  return 0;
-}
-_ACEOF
-if ac_fn_c_try_link "$LINENO"
-then :
-  ac_cv_lib_c__Block_release=yes
-else $as_nop
-  ac_cv_lib_c__Block_release=no
-fi
-rm -f core conftest.err conftest.$ac_objext conftest.beam \
-    conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_c__Block_release" >&5
-printf "%s\n" "$ac_cv_lib_c__Block_release" >&6; }
-if test "x$ac_cv_lib_c__Block_release" = xyes
-then :
-  printf "%s\n" "#define HAVE_LIBC 1" >>confdefs.h
-
-  LIBS="-lc $LIBS"
-
-else $as_nop
-
-      echo "Required library liblocksruntime not installed" >&2
-      exit 1
-
-fi
-
-
-
-fi
-
-
-
 
 ### Check for libfts (musl) ###
 
